INSERT INTO KOMMUN(NAME, TAXRATE) VALUES('Österåker', 0.7102);
INSERT INTO KOMMUN(NAME, TAXRATE) VALUES('Solna', 0.708);
INSERT INTO KOMMUN(NAME, TAXRATE) VALUES('Täby', 0.7037);
INSERT INTO KOMMUN(NAME, TAXRATE) VALUES('Stockholm', 0.7018);
INSERT INTO KOMMUN(NAME, TAXRATE) VALUES('Huddinge', 0.6845);




